Ön hazırlık (kütüphane kurulumu)

In [3]:
# Gerekli kütüphaneleri yükleyelim (Colab hücresine)
!pip install cirq qiskit qutip numpy matplotlib --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 32.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.8/670.8 kB 38.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 430.5/430.5 kB 29.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 110.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.8/31.8 MB 59.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 60.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 87.3 MB/s eta 0:00:00


In [4]:
# cirq_examples.py
import numpy as np
import cirq

def print_header(h):
    print("\n" + "="*10 + " " + h + " " + "="*10)

# 1) 3x3 matris determinant (örnek A)
A = np.array([[2,1,5],[4,3,6],[0,2,7]])
print_header("Örnek 1: det(A)")
print("A =\n", A)
print("det(A) =", int(round(np.linalg.det(A))))  # beklenen 30

# 2) İz hesabı (B)
B = np.array([[4,1],[-2,5]])
print_header("Örnek 2: Tr(B)")
print("B =\n", B)
print("Tr(B) =", np.trace(B))  # 9

# 3) Simetrik kontrol (C)
C = np.array([[1,2],[2,3]])
print_header("Örnek 3: Simetrik mi?")
print("C =\n", C)
print("C^T =\n", C.T)
print("Simetrik mi?", np.allclose(C, C.T))

# 4) Hermitik kontrol (D)
D = np.array([[1, 1j],[-1j, 2]])
print_header("Örnek 4: Hermitik mi?")
print("D =\n", D)
print("D^† =\n", D.conj().T)
print("Hermitik mi?", np.allclose(D, D.conj().T))

# 5) Matris boyutu ve tanımlı olduğu uzay
M = np.array([[1, 2+3j, -1],[0,4,5j],[3,-2,0]])
print_header("Örnek 5: Boyut ve uzay")
print("M.shape =", M.shape)
print("Eleman türü (örnek):", type(M[0,1]))
print("Tanımlı uzay: C^{}x{}".format(*M.shape))

# 6) Toplama ve fark (A and B)
A2 = np.array([[1,2],[3,4]])
B2 = np.array([[4,3],[2,1]])
print_header("Örnek 6: A+B ve A-B")
print("A2+B2 =\n", A2 + B2)
print("A2-B2 =\n", A2 - B2)

# 7) Matris çarpımı (A*B)
A3 = np.array([[1,2],[3,4]])
B3 = np.array([[2,0],[1,2]])
print_header("Örnek 7: A3 * B3")
print("A3*B3 =\n", A3.dot(B3))

# 8) Transpoz ve hermitik eşlenik
A4 = np.array([[1, 1j],[-1j, 2]])
print_header("Örnek 8: Transpoz ve Adjoints")
print("A4 =\n", A4)
print("A4^T =\n", A4.T)
print("A4^† =\n", A4.conj().T)

# 9) Determinant örneği (2x2)
A5 = np.array([[2,3],[1,4]])
print_header("Örnek 9: det(A5)")
print("det(A5) =", np.linalg.det(A5))  # 5

# 10) Trace örneği
A6 = np.array([[1,2],[3,4]])
print_header("Örnek 10: Tr(A6)")
print("Tr(A6) =", np.trace(A6))  # 5

# Ek: Cirq unitary örneği (Pauli-X matrisi)
print_header("Cirq: Pauli-X matrisi")
print(cirq.unitary(cirq.X))



========== Örnek 1: det(A) ==========
A =
 [[2 1 5]
 [4 3 6]
 [0 2 7]]
det(A) = 30

========== Örnek 2: Tr(B) ==========
B =
 [[ 4  1]
 [-2  5]]
Tr(B) = 9

========== Örnek 3: Simetrik mi? ==========
C =
 [[1 2]
 [2 3]]
C^T =
 [[1 2]
 [2 3]]
Simetrik mi? True

========== Örnek 4: Hermitik mi? ==========
D =
 [[ 1.+0.j  0.+1.j]
 [-0.-1.j  2.+0.j]]
D^† =
 [[ 1.-0.j -0.+1.j]
 [ 0.-1.j  2.-0.j]]
Hermitik mi? True

========== Örnek 5: Boyut ve uzay ==========
M.shape = (3, 3)
Eleman türü (örnek): <class 'numpy.complex128'>
Tanımlı uzay: C^3x3

========== Örnek 6: A+B ve A-B ==========
A2+B2 =
 [[5 5]
 [5 5]]
A2-B2 =
 [[-3 -1]
 [ 1  3]]

========== Örnek 7: A3 * B3 ==========
A3*B3 =
 [[ 4  4]
 [10  8]]

========== Örnek 8: Transpoz ve Adjoints ==========
A4 =
 [[ 1.+0.j  0.+1.j]
 [-0.-1.j  2.+0.j]]
A4^T =
 [[ 1.+0.j -0.-1.j]
 [ 0.+1.j  2.+0.j]]
A4^† =
 [[ 1.-0.j -0.+1.j]
 [ 0.-1.j  2.-0.j]]

========== Örnek 9: det(A5) ==========
det(A5) = 5.000000000000001

========== Örnek 10: Tr(A6) ===

In [5]:
# qiskit_examples.py
import numpy as np
from qiskit.quantum_info import Operator
import qiskit
import warnings
warnings.filterwarnings("ignore")

def ph(h): print("\n" + "="*10 + " " + h + " " + "="*10)

# 1) det 3x3
A = np.array([[2,1,5],[4,3,6],[0,2,7]])
ph("Determinant (A)")
print("det(A) =", int(round(np.linalg.det(A))))

# 2) trace B
B = np.array([[4,1],[-2,5]])
ph("Trace (B)")
print("Tr(B) =", np.trace(B))

# 3) symmetric check
C = np.array([[1,2],[2,3]])
ph("Symmetric?")
print("C^T =\n", C.T)
print("Symmetric?", np.allclose(C, C.T))

# 4) Hermitian check
D = np.array([[1, 1j],[-1j, 2]])
ph("Hermitian?")
print("D^† =\n", D.conj().T)
print("Hermitian?", np.allclose(D, D.conj().T))

# 5) shape and space
M = np.array([[1, 2+3j, -1],[0,4,5j],[3,-2,0]])
ph("Shape & Space")
print("shape:", M.shape, "-> space: C^{}x{}".format(*M.shape))

# 6) A+B and A-B
A2 = np.array([[1,2],[3,4]])
B2 = np.array([[4,3],[2,1]])
ph("A2+B2 / A2-B2")
print("A2+B2 =\n", A2 + B2)
print("A2-B2 =\n", A2 - B2)

# 7) Product
A3 = np.array([[1,2],[3,4]])
B3 = np.array([[2,0],[1,2]])
ph("A3*B3")
print(A3.dot(B3))

# 8) Transpose & Adjoint
A4 = np.array([[1, 1j],[-1j, 2]])
ph("Transpose & Adjoint")
print("A4^T =\n", A4.T)
print("A4^† =\n", A4.conj().T)

# 9) det 2x2
A5 = np.array([[2,3],[1,4]])
ph("det(A5)")
print(np.linalg.det(A5))

# 10) trace example
A6 = np.array([[1,2],[3,4]])
ph("trace(A6)")
print(np.trace(A6))

# Bonus: Qiskit Operator example (Pauli-X)
ph("Qiskit Operator (X)")
X = Operator(np.array([[0,1],[1,0]]))
print("Operator X matrix:\n", X.data)
print("Unitary?:", X.is_unitary())



========== Determinant (A) ==========
det(A) = 30

========== Trace (B) ==========
Tr(B) = 9

========== Symmetric? ==========
C^T =
 [[1 2]
 [2 3]]
Symmetric? True

========== Hermitian? ==========
D^† =
 [[ 1.-0.j -0.+1.j]
 [ 0.-1.j  2.-0.j]]
Hermitian? True

========== Shape & Space ==========
shape: (3, 3) -> space: C^3x3

========== A2+B2 / A2-B2 ==========
A2+B2 =
 [[5 5]
 [5 5]]
A2-B2 =
 [[-3 -1]
 [ 1  3]]

========== A3*B3 ==========
[[ 4  4]
 [10  8]]

========== Transpose & Adjoint ==========
A4^T =
 [[ 1.+0.j -0.-1.j]
 [ 0.+1.j  2.+0.j]]
A4^† =
 [[ 1.-0.j -0.+1.j]
 [ 0.-1.j  2.-0.j]]

========== det(A5) ==========
5.000000000000001

========== trace(A6) ==========
5

========== Qiskit Operator (X) ==========
Operator X matrix:
 [[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]
Unitary?: True


In [6]:
# qutip_examples.py
import numpy as np
import qutip as qt

def ph(h): print("\n" + "="*10 + " " + h + " " + "="*10)

# 1) determinant (3x3)
A = np.array([[2,1,5],[4,3,6],[0,2,7]])
A_q = qt.Qobj(A)
ph("det(A)")
# QuTiP Qobj için doğrudan det yok, numpy ile alıyoruz
print("det(A) =", int(round(np.linalg.det(A))))

# 2) trace
B = qt.Qobj(np.array([[4,1],[-2,5]]))
ph("Tr(B)")
print("Tr(B) =", B.tr())

# 3) symmetric check (use .full())
C = qt.Qobj(np.array([[1,2],[2,3]]))
ph("Symmetric?")
print("C.full() =\n", C.full())
print("Symmetric?", np.allclose(C.full(), C.full().T))

# 4) Hermitian check
D = qt.Qobj(np.array([[1, 1j],[-1j, 2]]))
ph("Hermitian?")
print("D.dag() =\n", D.dag().full())
print("Hermitian?", D.isherm)

# 5) shape & space
M = qt.Qobj(np.array([[1, 2+3j, -1],[0,4,5j],[3,-2,0]]))
ph("Shape & Space")
print("shape:", M.shape)
print("Space: C^{}x{}".format(*M.shape))

# 6) addition / subtraction
A2 = qt.Qobj(np.array([[1,2],[3,4]]))
B2 = qt.Qobj(np.array([[4,3],[2,1]]))
ph("A2+B2 / A2-B2")
print((A2 + B2).full())
print((A2 - B2).full())

# 7) product
A3 = qt.Qobj(np.array([[1,2],[3,4]]))
B3 = qt.Qobj(np.array([[2,0],[1,2]]))
ph("A3*B3")
print((A3 * B3).full())

# 8) transpose & adjoint
A4 = qt.Qobj(np.array([[1, 1j],[-1j, 2]]))
ph("A4^T and A4^†")
print("A4.transpose() =\n", A4.trans().full())
print("A4.dag() =\n", A4.dag().full())

# 9) det and 10) trace
ph("det & trace")
print("det(A5) =", np.linalg.det(np.array([[2,3],[1,4]])))
print("trace(A6) =", qt.Qobj(np.array([[1,2],[3,4]])).tr())

# Bonus: komütatör örneği (Pauli-X, Pauli-Y)
ph("Commutator [X,Y]")
X = qt.sigmax(); Y = qt.sigmay()
print((X*Y - Y*X).full())



========== det(A) ==========
det(A) = 30

========== Tr(B) ==========
Tr(B) = (9+0j)

========== Symmetric? ==========
C.full() =
 [[1.+0.j 2.+0.j]
 [2.+0.j 3.+0.j]]
Symmetric? True

========== Hermitian? ==========
D.dag() =
 [[ 1.-0.j -0.+1.j]
 [ 0.-1.j  2.-0.j]]
Hermitian? True

========== Shape & Space ==========
shape: (3, 3)
Space: C^3x3

========== A2+B2 / A2-B2 ==========
[[5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j]]
[[-3.+0.j -1.+0.j]
 [ 1.+0.j  3.+0.j]]

========== A3*B3 ==========
[[ 4.+0.j  4.+0.j]
 [10.+0.j  8.+0.j]]

========== A4^T and A4^† ==========
A4.transpose() =
 [[ 1.+0.j -0.-1.j]
 [ 0.+1.j  2.+0.j]]
A4.dag() =
 [[ 1.-0.j -0.+1.j]
 [ 0.-1.j  2.-0.j]]

========== det & trace ==========
det(A5) = 5.000000000000001
trace(A6) = (5+0j)

========== Commutator [X,Y] ==========
[[0.+2.j 0.+0.j]
 [0.+0.j 0.-2.j]]
