Ön hazırlık (kütüphane kurulumu)

In [1]:
# Gerekli kütüphaneleri yükleyelim (Colab hücresine)
!pip install cirq qiskit qutip numpy matplotlib --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 40.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.8/670.8 kB 44.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 430.5/430.5 kB 31.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 112.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.8/31.8 MB 53.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 80.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 84.7 MB/s eta 0:00:00


Cirq Örneği (Lineer Operatör Simülasyonu)

Cirq doğrudan lineer operatörlerle çalışmaktan çok kuantum devreleri üzerinden yapar. Burada X ve Z kapılarıyla lineer kombinasyon örneği gösterilebilir:

In [2]:
import cirq
import numpy as np

# Qubit tanımlama
q = cirq.LineQubit(0)

# Devre oluşturma
circuit = cirq.Circuit()

# X ve Z kapıları ekleme (A ve B operatörleri)
circuit.append(cirq.X(q))  # A
circuit.append(cirq.Z(q))  # B

print("Cirq Devresi:")
print(circuit)

# Simülasyon
sim = cirq.Simulator()
result = sim.simulate(circuit)
print("\nSon durum vektörü:")
print(np.around(result.final_state_vector, 3))


Cirq Devresi:
0: ───X───Z───

Son durum vektörü:
[ 0.+0.j -1.+0.j]


Qiskit Örneği (Lineer Operatör Etkisi)

Qiskit ile X ve Z kapılarını lineer operatörler gibi uygulayabiliriz:

In [3]:
from qiskit import QuantumCircuit, Aer, transpile, assemble

qc = QuantumCircuit(1)

# Lineer operatörler (A = X, B = Z)
qc.x(0)
qc.z(0)

print("Qiskit Devresi:")
print(qc.draw())

# Simülasyon
sim = Aer.get_backend('statevector_simulator')
result = sim.run(assemble(transpile(qc, sim))).result()
state = result.get_statevector()
print("\nSon durum vektörü:")
print(state)


ImportError: cannot import name 'Aer' from 'qiskit' (/usr/local/lib/python3.12/dist-packages/qiskit/__init__.py)

QuTiP Örneği (Lineer Operatörler)

QuTiP doğrudan lineer operatörlerle çalışmak için en uygun araçtır:

In [4]:
from qutip import basis, sigmax, sigmaz
import numpy as np

# Başlangıç durumu |0>
psi = basis(2, 0)

# Lineer operatörler
A = sigmax()  # X
B = sigmaz()  # Z

# Lineer kombinasyonlar ve çarpımlar
state_AB = A * B * psi  # AB|ψ>
state_BA = B * A * psi  # BA|ψ>
state_sum = (A + B) * psi  # (A + B)|ψ>

print("QuTiP ile Lineer Operatörler:")
print("AB|ψ> =", state_AB)
print("BA|ψ> =", state_BA)
print("(A + B)|ψ> =", state_sum)


QuTiP ile Lineer Operatörler:
AB|ψ> = Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]]
BA|ψ> = Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.]
 [-1.]]
(A + B)|ψ> = Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [1.]]
