Ön hazırlık (kütüphane kurulumu)

In [2]:
# Gerekli kütüphaneleri yükleyelim (Colab hücresine)
!pip install cirq qiskit qutip numpy matplotlib --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 26.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.8/670.8 kB 38.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 430.5/430.5 kB 23.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 85.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.8/31.8 MB 49.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 66.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 81.7 MB/s eta 0:00:00


Cirq ile Matris Gösterimi

Cirq’de cirq.unitary() ile kapıların matris gösterimini alabiliyoruz.

In [3]:
import cirq
import numpy as np

# Qubit tanımla
q = cirq.LineQubit(0)

# Kapıların matris gösterimleri
I = cirq.unitary(cirq.I)   # Birim operatör
X = cirq.unitary(cirq.X)   # Pauli-X
H = cirq.unitary(cirq.H)   # Hadamard

# Örnek Hermitik matris (elle tanımlı)
A = np.array([[2, 1j], [-1j, 3]])

# Örnek birimsel matris (Hadamard benzeri)
U = (1/np.sqrt(2)) * np.array([[1, 1], [-1, 1]])

print("Cirq ile Matris Gösterimleri:")
print("I =\n", I)
print("X =\n", X)
print("H =\n", H)
print("Hermitik A =\n", A)
print("Unitary U =\n", U)

# Özellik kontrolü
print("\nA Hermitik mi? ->", np.allclose(A, A.conj().T))
print("U Birimsel mi? ->", np.allclose(U.conj().T @ U, np.eye(2)))


Cirq ile Matris Gösterimleri:
I =
 [[1. 0.]
 [0. 1.]]
X =
 [[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]
H =
 [[ 0.70710678+0.j  0.70710678+0.j]
 [ 0.70710678+0.j -0.70710678+0.j]]
Hermitik A =
 [[ 2.+0.j  0.+1.j]
 [-0.-1.j  3.+0.j]]
Unitary U =
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

A Hermitik mi? -> True
U Birimsel mi? -> True


Qiskit ile Matris Gösterimi

Qiskit’te Operator sınıfı kullanılarak kapıların ve matrislerin doğruluğu kontrol edilebilir.

In [4]:
from qiskit.quantum_info import Operator
import numpy as np

# Birim operatör
I = np.eye(2)

# Hermitik operatör
A = np.array([[2, 1j], [-1j, 3]])

# Birimsel operatör
U = (1/np.sqrt(2)) * np.array([[1, 1], [-1, 1]])

print("Qiskit ile Matris Gösterimleri:")
print("I =\n", I)
print("A =\n", A)
print("U =\n", U)

# Özellik kontrolleri
print("\nA Hermitik mi? ->", np.allclose(A, A.conj().T))
print("U Birimsel mi? ->", np.allclose(U.conj().T @ U, np.eye(2)))


Qiskit ile Matris Gösterimleri:
I =
 [[1. 0.]
 [0. 1.]]
A =
 [[ 2.+0.j  0.+1.j]
 [-0.-1.j  3.+0.j]]
U =
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

A Hermitik mi? -> True
U Birimsel mi? -> True


QuTiP ile Matris Gösterimi

QuTiP, operatörlerin matematiksel özelliklerini kontrol etmek için çok uygundur.

In [6]:
from qutip import qeye, Qobj
import numpy as np

# Birim operatör
I = qeye(2)

# Hermitik operatör
A = Qobj([[2, 1j], [-1j, 3]])

# Birimsel operatör
U = Qobj((1/np.sqrt(2)) * np.array([[1, 1], [-1, 1]]))

print("QuTiP ile Matris Gösterimleri:")
print("I =\n", I)
print("A =\n", A)
print("U =\n", U)

# Özellik kontrolleri
print("\nA Hermitik mi? ->", A.isherm)
print("U Birimsel mi? ->", U.isunitary())


QuTiP ile Matris Gösterimleri:
I =
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dia, isherm=True
Qobj data =
[[1. 0.]
 [0. 1.]]
A =
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 2.+0.j  0.+1.j]
 [-0.-1.j  3.+0.j]]
U =
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=False
Qobj data =
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

A Hermitik mi? -> True


TypeError: 'bool' object is not callable