Ön hazırlık (kütüphane kurulumu)

In [1]:
# Gerekli kütüphaneleri yükleyelim (Colab hücresine)
!pip install cirq qiskit qutip numpy matplotlib --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 27.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.8/670.8 kB 37.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 430.5/430.5 kB 24.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 95.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.8/31.8 MB 53.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 61.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 81.5 MB/s eta 0:00:00


1. Matris Toplama ve Çıkarma
Qiskit (Toplama–Çıkarma)

In [2]:
import numpy as np

# Matrisler
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

C = A + B  # Toplama
D = A - B  # Çıkarma

print("A + B =\n", C)
print("A - B =\n", D)



A + B =
 [[ 6  8]
 [10 12]]
A - B =
 [[-4 -4]
 [-4 -4]]


Cirq (NumPy üzerinden matris işlemleri)

In [3]:
import numpy as np

A = np.array([[1, 0],
              [0, 1]])
B = np.array([[0, 1],
              [1, 0]])

print("A + B =\n", A + B)
print("A - B =\n", A - B)


A + B =
 [[1 1]
 [1 1]]
A - B =
 [[ 1 -1]
 [-1  1]]


QuTiP (Qobj ile işlemler)

In [4]:
import qutip as qt

A = qt.Qobj([[1, 2],
             [3, 4]])
B = qt.Qobj([[5, 6],
             [7, 8]])

C = A + B
D = A - B

print("A + B =\n", C.full())
print("A - B =\n", D.full())


A + B =
 [[ 6.+0.j  8.+0.j]
 [10.+0.j 12.+0.j]]
A - B =
 [[-4.+0.j -4.+0.j]
 [-4.+0.j -4.+0.j]]


2. Matris Çarpımı
Qiskit (Matris Çarpımı)

In [5]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[0, 1],
              [1, 0]])

C = np.dot(A, B)
print("A * B =\n", C)


A * B =
 [[2 1]
 [4 3]]


Cirq (unitary çarpımı)

In [6]:
import numpy as np
import cirq

X = cirq.unitary(cirq.X)  # Pauli-X matrisi
Y = cirq.unitary(cirq.Y)  # Pauli-Y matrisi

C = np.dot(X, Y)
print("X * Y =\n", C)


X * Y =
 [[0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j]]


QuTiP (Operatör çarpımı)

In [7]:
import qutip as qt

X = qt.sigmax()
Y = qt.sigmay()

C = X * Y
print("X * Y =\n", C.full())


X * Y =
 [[0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j]]
