Ön hazırlık (kütüphane kurulumu)

In [ ]:
pip install cirq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 18.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.8/670.8 kB 44.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 430.5/430.5 kB 29.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 60.6 MB/s eta 0:00:00


CIRQ ÖRNEKLERİ
1. Süperpozisyon (Hadamard Kapısı)

In [ ]:
# CIRQ Süperpozisyon Örneği
# =========================
# Qubit başlangıçta |0> durumunda.
# Hadamard (H) kapısı uygularsak qubit,
# (|0> + |1>)/√2 süperpozisyon durumuna geçer.
# Ölçüm sonucunda %50 olasılıkla '0', %50 olasılıkla '1' elde ederiz.

!pip install cirq --quiet

import cirq

# Qubit tanımla
q = cirq.LineQubit(0)

# Devre: Hadamard + ölçüm
circuit = cirq.Circuit(cirq.H(q), cirq.measure(q, key='m'))
print("Devre:\n", circuit)

# Simülatör
sim = cirq.Simulator()

# 1000 ölçüm yapalım
result = sim.run(circuit, repetitions=1000)
print("Ölçüm sonuçları (yaklaşık yarı yarıya):")
print(result.histogram(key='m'))


Devre:
 0: ───H───M('m')───
Ölçüm sonuçları (yaklaşık yarı yarıya):
Counter({0: 505, 1: 495})


2. Dolanıklık (Bell State)

In [ ]:
# CIRQ Dolanıklık (Bell State) Örneği
# ===================================
# İki qubit başlangıçta |00> durumunda.
# İlk qubit'e Hadamard uygularız -> (|0>+|1>)/√2
# Sonra CNOT uygularız -> (|00>+|11>)/√2
# Bu iki qubit artık dolanık hale gelir.
# Ölçümde ya 00 ya da 11 sonucunu görürüz.

import cirq

# Qubitler
q0, q1 = cirq.LineQubit.range(2)

# Devre: H -> CNOT -> ölçüm
circuit = cirq.Circuit(cirq.H(q0), cirq.CNOT(q0, q1), cirq.measure(q0, q1, key='m'))
print("Devre:\n", circuit)

# Simülatör
sim = cirq.Simulator()

# Ölçüm
result = sim.run(circuit, repetitions=1000)
print("Ölçüm sonuçları (00 ve 11 ağırlıklı):")
print(result.multi_measurement_histogram(keys=['m']))


Devre:
 0: ───H───@───M('m')───
          │   │
1: ───────X───M────────
Ölçüm sonuçları (00 ve 11 ağırlıklı):
Counter({(0,): 505, (3,): 495})


3. Girişim (H Z H)

In [ ]:
# CIRQ Girişim Örneği
# ===================
# Devre: H -> Z -> H
# Matematiksel olarak HZH = X (NOT kapısı).
# Yani |0> durumunu |1>'e çevirir.
# Ölçüm sonucunda her zaman '1' elde etmeliyiz.

import cirq

q = cirq.LineQubit(0)
circuit = cirq.Circuit(cirq.H(q), cirq.Z(q), cirq.H(q), cirq.measure(q, key='m'))
print("Devre:\n", circuit)

sim = cirq.Simulator()
result = sim.run(circuit, repetitions=100)
print("Ölçüm sonuçları (hepsi '1'):")
print(result.histogram(key='m'))


Devre:
 0: ───H───Z───H───M('m')───
Ölçüm sonuçları (hepsi '1'):
Counter({1: 100})


QISKIT ÖRNEKLERİ
1. Süperpozisyon (Hadamard Kapısı)

In [1]:
# QISKIT Süperpozisyon Örneği
# ===========================
# Qubit |0> durumunda başlar.
# Hadamard kapısı ile (|0> + |1>)/√2 süperpozisyonuna geçer.
# Ölçüm sonucunda 0 ve 1 yaklaşık yarı yarıya çıkar.

!pip install qiskit --quiet

from qiskit import QuantumCircuit, transpile
from qiskit.providers.aer import AerSimulator

# Devre
qc = QuantumCircuit(1,1)
qc.h(0)
qc.measure(0,0)
qc.draw('mpl')


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 21.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 24.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 kB 2.0 MB/s eta 0:00:00


ModuleNotFoundError: No module named 'qiskit.providers.aer'

In [ ]:
# Simülasyon ve sonuçlar
sim = AerSimulator()
compiled = transpile(qc, sim)
result = sim.run(compiled, shots=1000).result()
counts = result.get_counts()
print("Ölçüm sonuçları (yaklaşık 50/50):", counts)


NameError: name 'AerSimulator' is not defined

2. Dolanıklık (Bell State)

In [ ]:
# QISKIT Dolanıklık Örneği
# ========================
# İki qubit başlangıçta |00>
# İlk qubit'e H uygula -> (|0>+|1>)/√2
# CNOT uygula -> (|00>+|11>)/√2
# Ölçümde sadece 00 veya 11 çıkar.

from qiskit import QuantumCircuit

# Devre
qc = QuantumCircuit(2,2)
qc.h(0)
qc.cx(0,1)
qc.measure([0,1], [0,1])
qc.draw('mpl')


MissingOptionalLibraryError: "The 'pylatexenc' library is required to use 'MatplotlibDrawer'. You can install it with 'pip install pylatexenc'."

In [ ]:
# Simülasyon
compiled = transpile(qc, sim)
result = sim.run(compiled, shots=1000).result()
counts = result.get_counts()
print("Ölçüm sonuçları (00 ve 11):", counts)


AttributeError: 'Simulator' object has no attribute 'num_qubits'

3. Girişim (H Z H)

In [ ]:
# QISKIT Girişim Örneği
# =====================
# Devre: H -> Z -> H
# Bu kombinasyon NOT kapısına eşittir.
# Yani |0> -> |1>
# Ölçümde hep '1' çıkar.

qc = QuantumCircuit(1,1)
qc.h(0)
qc.z(0)
qc.h(0)
qc.measure(0,0)
qc.draw('mpl')


MissingOptionalLibraryError: "The 'pylatexenc' library is required to use 'MatplotlibDrawer'. You can install it with 'pip install pylatexenc'."

In [ ]:
# Simülasyon
compiled = transpile(qc, sim)
result = sim.run(compiled, shots=100).result()
counts = result.get_counts()
print("Ölçüm sonuçları (hepsi '1'):", counts)


AttributeError: 'Simulator' object has no attribute 'num_qubits'

QuTiP ÖRNEKLERİ (Colab)

Ön hazırlık (kütüphane kurulumu)

In [ ]:
# QuTiP kütüphanesini yükleyelim
!pip install qutip --quiet


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.8/31.8 MB 49.2 MB/s eta 0:00:00


1. Süperpozisyon

In [ ]:
# Süperpozisyon Örneği (QuTiP)
# ============================
# |0> durumuna Hadamard benzeri dönüşüm uygularsak
# (|0> + |1>)/√2 süperpozisyonunu elde ederiz.

import numpy as np
from qutip import basis, Qobj

# |0> ve |1> baz durumları
zero = basis(2,0)
one  = basis(2,1)

# Hadamard matrisi (Qobj olarak)
H = Qobj((1/np.sqrt(2)) * np.array([[1, 1],
                                    [1, -1]]))

# |0> üzerine uygula
psi = H * zero
print("Süperpozisyon durumu (|0> -> (|0>+|1>)/√2):")
print(psi)

# Olasılıklar
probs = np.abs(psi.full())**2
print("Ölçüm olasılıkları (0 ve 1):", probs.flatten())


Süperpozisyon durumu (|0> -> (|0>+|1>)/√2):
Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678]
 [0.70710678]]
Ölçüm olasılıkları (0 ve 1): [0.5 0.5]


2. Dolanıklık (Bell State)

In [ ]:
# Dolanıklık Örneği (QuTiP)
# =========================
# Bell durumu: (|00> + |11>)/√2

from qutip import tensor

# Baz durumlar
zero = basis(2,0)
one  = basis(2,1)

# Bell durumu tanımı
bell = (tensor(zero, zero) + tensor(one, one)).unit()

print("Bell durumu (|00>+|11>)/√2:")
print(bell)

# Yoğunluk matrisi (görselleştirme için)
rho = bell * bell.dag()
rho


Bell durumu (|00>+|11>)/√2:
Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]


Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]

3. Girişim (H Z H)

In [ ]:
# Girişim Örneği (QuTiP)
# ======================
# H Z H = X (NOT kapısı).
# Yani |0> -> |1>

# Z kapısı
Z = Qobj(np.array([[1, 0],
                   [0, -1]]))

# X kapısı (kontrol için)
X = Qobj(np.array([[0, 1],
                   [1, 0]]))

# Hadamard
H = Qobj((1/np.sqrt(2)) * np.array([[1, 1],
                                    [1, -1]]))

# H Z H işlemi
HZH = H * Z * H

# Başlangıç: |0>
zero = basis(2,0)

# Uygula
psi = HZH * zero

print("HZH |0> sonucu:")
print(psi)

print("Beklenen sonuç (|1>):")
print(one)


HZH |0> sonucu:
Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[-2.23711432e-17]
 [ 1.00000000e+00]]
Beklenen sonuç (|1>):
Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]]


4. Ölçüm (Projeksiyon)

In [ ]:
!pip install scipy==1.2.1
!pip install qutip

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 74.2 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
# Ölçüm Örneği (QuTiP)
# ====================
# Süperpozisyon durumunu ölçelim.
# Ölçüm, durumu '0' veya '1'e indirger.
import qutip
from qutip import measurement_statistics

# Başlangıç durumu: süperpozisyon
psi = (zero + one).unit()

# Ölçüm operatörleri: |0><0| ve |1><1|
P0 = zero*zero.dag()
P1 = one*one.dag()

# Olasılık dağılımı
p0, state0 = measurement_statistics(psi, [P0, P1])[0]
p1, state1 = measurement_statistics(psi, [P0, P1])[1]

print("Ölçüm olasılıkları:")
print("P(0) =", p0)
print("P(1) =", p1)


ImportError: cannot import name 'measurement_statistics' from 'qutip' (/usr/local/lib/python3.12/dist-packages/qutip/__init__.py)