Ön hazırlık (kütüphane kurulumu)

In [1]:
# Gerekli kütüphaneleri yükleyelim (Colab hücresine)
!pip install cirq qiskit qutip numpy matplotlib --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 47.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.8/670.8 kB 32.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 430.5/430.5 kB 30.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 108.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.8/31.8 MB 59.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 78.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 90.6 MB/s eta 0:00:00


Matrislerle İlgili Özellikler
 1. Skaler Çarpım

In [2]:
# Qiskit (NumPy)
import numpy as np
A = np.array([[1, 2],
              [3, 4]])
alpha = 2
print(alpha * A)

# Cirq
print(alpha * A)  # Cirq için NumPy kullanılır

# QuTiP
import qutip as qt
A_q = qt.Qobj(A)
print((alpha * A_q).full())


[[2 4]
 [6 8]]
[[2 4]
 [6 8]]
[[2.+0.j 4.+0.j]
 [6.+0.j 8.+0.j]]


2. Transpoz (Transpose)

In [3]:
# Qiskit (NumPy)
print(A.T)

# Cirq
print(A.T)

# QuTiP
print(A_q.trans().full())


[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1.+0.j 3.+0.j]
 [2.+0.j 4.+0.j]]


3. Kompleks Eşlenik

In [4]:
A_complex = np.array([[1+2j, 2-1j],
                      [3+0j, 4-2j]])

# Qiskit
print(np.conjugate(A_complex))

# Cirq
print(np.conjugate(A_complex))

# QuTiP
A_cq = qt.Qobj(A_complex)
print(A_cq.conj().full())


[[1.-2.j 2.+1.j]
 [3.-0.j 4.+2.j]]
[[1.-2.j 2.+1.j]
 [3.-0.j 4.+2.j]]
[[1.-2.j 2.+1.j]
 [3.-0.j 4.+2.j]]


4. Hermitik Eşlenik (Adjoint)

In [5]:
# Qiskit
print(A_complex.conj().T)

# Cirq
print(A_complex.conj().T)

# QuTiP
print(A_cq.dag().full())


[[1.-2.j 3.-0.j]
 [2.+1.j 4.+2.j]]
[[1.-2.j 3.-0.j]
 [2.+1.j 4.+2.j]]
[[1.-2.j 3.-0.j]
 [2.+1.j 4.+2.j]]


5. Hermitik Matris

In [6]:
H = np.array([[2, 1j],
              [-1j, 3]])
print(np.allclose(H, H.conj().T))  # True ise Hermitik

# QuTiP
H_q = qt.Qobj(H)
print(H_q.isherm)


True
True


6. Birimsel (Unitary) Matris

In [7]:
from qiskit.quantum_info import Operator

H = (1/np.sqrt(2)) * np.array([[1, 1],
                                [1, -1]])
print(np.allclose(H.conj().T @ H, np.eye(2)))  # True

# Cirq
import cirq
print(np.allclose(cirq.unitary(cirq.H), H))

# QuTiP
H_q = qt.Qobj(H)
print(H_q.isunitary)


True
True
True


7. Simetrik Matris

In [8]:
S = np.array([[1, 2],
              [2, 3]])
print(np.allclose(S, S.T))  # True


True


8. Asimetrik (Antisymmetric) Matris

In [9]:
AS = np.array([[0, -2],
               [2,  0]])
print(np.allclose(AS.T, -AS))  # True


True


9. Ortogonal Matris

In [10]:
theta = np.pi/4
O = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])
print(np.allclose(O.T @ O, np.eye(2)))


True
